### ISSUE TITLE
build little shiny app based on powerpoint initial design ideas

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrccensus#32]
just like dropdowns and checkboxes that don't do anything.
need a new repo for this. psrccensus_explorer (that's long but an initial idea)

we need to make the lookup tables concept (suzanne)

**Comment by cyyllam** [comment]
@Ennazus A dummy app with filler content. The code is available https://github.com/psrc/psrccensus-app. As long as you VPN, all should work when you git clone and run on your machine.

![image](https://user-images.githubusercontent.com/17414750/133701484-e99f2c66-ba9c-4548-8ef0-1202fe0abe6d.png)

**Comment by cyyllam** [comment]
@Ennazus renamed it to `psrccensus-explorer` cuz I just noticed your suggestion!
https://github.com/psrc/psrccensus-explorer
