### ISSUE TITLE
clean up documentation based on Mary's feedback

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrccensus#35]
One the home page your sent (https://psrc.github.io/psrccensus/index.html), the example install code line "devtools::install_github(“psrc/psrccensus”)" includes quotation marks that don't work in R - this isn't a huge issue, but does produce an error when copying/pasting into R
	
the link at the bottom of this text redirects the user to this same page - I'm not sure if it's meant to bring the user to another page or if it hasn't been developed yet and the hyperlink is a placeholder for now?

**Comment by Ennazus** [comment]
he period between table.names and years is supposed to be a comma based on the code example shown below

​
    ^ On the Getting Started page

**Comment by Ennazus** [comment]
More notes:[Mary's notes on improvement](https://github.com/psrc/psrccensus/blob/main/docs/Thoughts%20about%20the%20psrccensus%20tool.docx)

**Comment by cyyllam** [comment]
Same as Issue #38
