### ISSUE TITLE
remove sys.getenv() calls in the roxygen documentation

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrccensus#46]
you can do is use one of the tidycensus functions --just once in the console. With the install argument, it's going to store the key in a .Renviron file. Afterwards you won't need to use sys.getenv() everytime or display your key in scripts. I've added this as a alternate method under 'Set up your API Key' in https://psrc.github.io/psrccensus/articles/psrccensus.html
tidycensus::census_api_key('your api key', install = TRUE)

**Comment by jensenmj** [comment]
Solved with commit #844c92d.
