### ISSUE TITLE
Reprexes not working, changes in API?

### ISSUE THREAD

**Issue by cyyllam** [psrc/psrccensus#55]
Underlying column names or structure is preventing example code from working
`# Error in `select()`:
#   ! Can't subset columns that don't exist.
# ✖ Column `geography` doesn't exist.
x <- get_acs_recs(geography = 'county',
             table.names = c('B03002'),
             years=c(2017,2019),
             acs.type = 'acs1')

**Comment by jensenmj** [comment]
Yes, it was on the Census Bureau side. Working now.
