### ISSUE TITLE
labels are duplicated for ACS Place data (user ends up with two columns for label and concept)

### ISSUE THREAD

**Issue by chelmann** [psrc/psrccensus#60]
looks like the labels are probably merged twice for some reason.

**Comment by Ennazus** [comment]
thanks @chelmann can you provide a reprex? I do notice that line 213 has

# Add labels to the data - The labels can differ for each year so loading now
      labels <- tidycensus::load_variables(year=year, dataset=acs.type)

AND line 221 has
# Add labels, column for Census Geography, Type and Year of Data
      tbl %<>% label_acs_variables(table, year, acs.type) %>%
probably just added twice accidentally?? but I'm not sure, @jensenmj  ?
