### ISSUE TITLE
Build a Shiny app on top of the ACS functions

### ISSUE THREAD

**Issue by Ennazus** [psrc/psrccensus#9]

**Comment by cyyllam** [comment]
@Ennazus @chelmann As the app is being built, one observation is that the FIPS/fips argument in `get_acs_recs()` and `get_decennial_recs()` is used differently. 

They yield two different results:

1. `get_decennial_recs(geography = 'place',
                   table_codes = 'PCT013',
                   year = 2010,
                   fips = c("5363000", "5308850"))` 
2. `get_acs_recs(geography = 'place',
             table.names = 'B01003',
             years = '2019',
             FIPS = c('5363000', '5308850'), 
             acs.type = 'acs1')`
